# This is a config for E2B sandbox template.
# You can use template ID (4jk3hk56htej530a378p) or template name (vibe-nextjs-test-4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-4") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-4')

team_id = "b2a74706-45cb-4bd1-807c-affc6707b156"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-4"
template_id = "4jk3hk56htej530a378p"
